//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecorridoWPF.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecorridoHyundai30
    {
        public int IdRecorrido { get; set; }
        public string LugarSalida { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public int TanqueSalida_Km_ { get; set; }
        public int KilometrajeSalida_Km_ { get; set; }
        public string Ruta { get; set; }
        public string LugarLlegada { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public System.TimeSpan HoraLlegada { get; set; }
        public int TanqueLlegada_Km_ { get; set; }
        public int KilometrajeLlegada_Km_ { get; set; }
    }
}
